from __future__ import annotations

from datetime import date
from typing import TYPE_CHECKING
from uuid import UUID

from sqlalchemy import Date, ForeignKey, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database.base import AuditModel

if TYPE_CHECKING:
    from app.models.company.company import Company
    from app.models.company.branch import Branch
    from app.models.purchase.purchase_requisition import PurchaseRequisition
    from app.models.purchase.supplier_quotation import SupplierQuotation
    from app.models.accounting.journal_status import JournalStatus


class RequestForQuotation(AuditModel):
    """
    Represents a Request For Quotation (RFQ) issued to one or more suppliers.

    Purpose:
        A Request For Quotation (RFQ) is created after an approved Purchase
        Requisition. It is used to invite suppliers to submit quotations for
        requested goods or services.

        An RFQ itself does not contain supplier pricing. Instead, suppliers
        respond with Supplier Quotations, allowing the purchasing department
        to compare prices, delivery schedules, payment terms, and other
        commercial conditions before selecting the best supplier.

        A single RFQ can result in multiple Supplier Quotations.

    ERP Workflow:

        Purchase Requisition
                │
                ▼
        Request For Quotation
                │
        ┌───────┼────────┐
        ▼       ▼        ▼
     Supplier  Supplier  Supplier
      Quote A   Quote B   Quote C
                │
                ▼
        Purchase Order
                │
                ▼
        Purchase Receipt
                │
                ▼
        Purchase Invoice

    Business Benefits:
        - Standardizes supplier quotation requests.
        - Supports competitive supplier bidding.
        - Improves procurement transparency.
        - Enables quotation comparison.
        - Reduces purchasing costs.
        - Maintains a complete procurement audit trail.

    Typical Usage:

        Purchasing Department
            Sends RFQs to approved suppliers.

        Suppliers
            Submit quotations against the RFQ.

        Purchase Manager
            Reviews supplier quotations and selects the
            most suitable supplier before creating
            the Purchase Order.

    Relationships:

        Purchase Requisition
                │
                ▼
        RequestForQuotation
                │
                └── SupplierQuotation

    Example:

        RFQ No:
            RFQ-2026-00015

        Requisition:
            PR-2026-00008

        RFQ Date:
            01-Aug-2026

        Valid Until:
            10-Aug-2026

        Sent To:
            • ABC Suppliers
            • XYZ Traders
            • PQR Industries

        Status:
            Open
    """

    __tablename__ = "request_for_quotations"

    rfq_no: Mapped[str] = mapped_column(
        String(30),
        nullable=False,
        unique=True,
        index=True,
        doc="Unique Request For Quotation number generated by the ERP.",
    )

    rfq_date: Mapped[date] = mapped_column(
        Date,
        nullable=False,
        doc="Date on which the RFQ was issued.",
    )

    company_id: Mapped[UUID] = mapped_column(
        ForeignKey("companies.id"),
        nullable=False,
        index=True,
        doc="Company issuing the RFQ.",
    )

    branch_id: Mapped[UUID] = mapped_column(
        ForeignKey("branches.id"),
        nullable=False,
        index=True,
        doc="Branch issuing the RFQ.",
    )

    requisition_id: Mapped[UUID] = mapped_column(
        ForeignKey("purchase_requisitions.id"),
        nullable=False,
        index=True,
        doc="Reference to the Purchase Requisition from which this RFQ was created.",
    )

    valid_until: Mapped[date | None] = mapped_column(
        Date,
        nullable=True,
        doc="Last date on which suppliers can submit quotations.",
    )

    remarks: Mapped[str | None] = mapped_column(
        String(500),
        nullable=True,
        doc="Additional notes or instructions for suppliers.",
    )

    status_id: Mapped[UUID] = mapped_column(
        ForeignKey("journal_statuses.id"),
        nullable=False,
        index=True,
        doc="Current workflow status of the RFQ.",
    )

    # ------------------------------------------------------------------
    # Relationships
    # ------------------------------------------------------------------

    company: Mapped["Company"] = relationship()

    branch: Mapped["Branch"] = relationship()

    purchase_requisition: Mapped["PurchaseRequisition"] = relationship(
        back_populates="request_for_quotations",
    )

    status: Mapped["JournalStatus"] = relationship()

    supplier_quotations: Mapped[list["SupplierQuotation"]] = relationship(
        back_populates="request_for_quotation",
        cascade="all, delete-orphan",
    )
