from __future__ import annotations

from typing import TYPE_CHECKING

from sqlalchemy import Boolean, Date, ForeignKey, Numeric, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database.base import AuditModel

if TYPE_CHECKING:
    from app.models.company import Company
    from app.models.branch import Branch
    from app.models.party.party import Party
    from app.models.common.currency import Currency
    from app.models.purchase.request_for_quotation import RequestForQuotation
    from app.models.purchase.supplier_quotation_item import SupplierQuotationItem
    from app.models.purchase.purchase_order import PurchaseOrder
    from app.models.accounting.journal_status import JournalStatus


class SupplierQuotation(AuditModel):
    """
    Represents a quotation submitted by a supplier in response to a
    Request For Quotation (RFQ).

    Purpose:
        A Supplier Quotation records the commercial offer provided by a
        supplier for supplying requested goods or services. Multiple
        suppliers may respond to a single RFQ, allowing the purchasing
        department to compare prices, taxes, discounts, delivery dates,
        payment terms, and other commercial conditions before selecting
        the most suitable supplier.

        Once approved, the selected Supplier Quotation becomes the basis
        for generating a Purchase Order.

    ERP Workflow:

        Purchase Requisition
                │
                ▼
        Request For Quotation
                │
        ┌───────┼────────┐
        ▼       ▼        ▼
     Supplier  Supplier  Supplier
      Quote A   Quote B   Quote C
                │
                ▼
        Compare Quotations
                │
                ▼
        Select Best Supplier
                │
                ▼
          Purchase Order
                │
                ▼
        Purchase Receipt
                │
                ▼
        Purchase Invoice

    Business Benefits:
        - Maintains supplier pricing history.
        - Supports competitive supplier evaluation.
        - Enables quotation comparison.
        - Stores supplier-specific references.
        - Tracks quotation validity.
        - Forms the basis for Purchase Orders.

    Typical Usage:

        Purchasing Department
            Receives quotations from multiple suppliers.

        Purchase Manager
            Compares quotations and selects the best supplier.

        Accounts Department
            References quotation pricing during invoice verification.

    Relationships:

        Request For Quotation
                │
                ▼
        SupplierQuotation
                ├── SupplierQuotationItem
                └── PurchaseOrder

    Example:

        Quotation No:
            SQ-2026-00018

        Supplier:
            ABC Suppliers

        RFQ:
            RFQ-2026-00005

        Valid Until:
            15-Aug-2026

        Grand Total:
            ₹1,25,000

        Status:
            Approved

        Selected:
            Yes
    """

    __tablename__ = "supplier_quotations"

    quotation_no: Mapped[str] = mapped_column(
        String(30),
        nullable=False,
        unique=True,
        index=True,
        doc="Unique supplier quotation number generated by the ERP.",
    )

    quotation_date: Mapped[date] = mapped_column(
        Date,
        nullable=False,
        doc="Date on which the supplier submitted the quotation.",
    )

    company_id: Mapped[int] = mapped_column(
        ForeignKey("companies.id"),
        nullable=False,
        index=True,
        doc="Company receiving the supplier quotation.",
    )

    branch_id: Mapped[int] = mapped_column(
        ForeignKey("branches.id"),
        nullable=False,
        index=True,
        doc="Branch responsible for the quotation.",
    )

    rfq_id: Mapped[int] = mapped_column(
        ForeignKey("request_for_quotations.id"),
        nullable=False,
        index=True,
        doc="Reference to the Request For Quotation.",
    )

    supplier_id: Mapped[int] = mapped_column(
        ForeignKey("parties.id"),
        nullable=False,
        index=True,
        doc="Supplier submitting the quotation.",
    )

    supplier_reference: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
        doc="Supplier's own quotation or reference number.",
    )

    valid_until: Mapped[date | None] = mapped_column(
        Date,
        nullable=True,
        doc="Quotation validity expiry date.",
    )

    currency_id: Mapped[int] = mapped_column(
        ForeignKey("currencies.id"),
        nullable=False,
        index=True,
        doc="Currency used in the quotation.",
    )

    exchange_rate: Mapped[float] = mapped_column(
        Numeric(18, 6),
        nullable=False,
        default=1,
        doc="Exchange rate applicable to the quotation currency.",
    )

    subtotal: Mapped[float] = mapped_column(
        Numeric(18, 2),
        nullable=False,
        default=0,
        doc="Total amount before discounts, taxes and additional charges.",
    )

    discount_amount: Mapped[float] = mapped_column(
        Numeric(18, 2),
        nullable=False,
        default=0,
        doc="Total discount offered by the supplier.",
    )

    tax_amount: Mapped[float] = mapped_column(
        Numeric(18, 2),
        nullable=False,
        default=0,
        doc="Total tax amount applicable to the quotation.",
    )

    other_charges: Mapped[float] = mapped_column(
        Numeric(18, 2),
        nullable=False,
        default=0,
        doc="Additional charges such as freight, insurance, packing, etc.",
    )

    grand_total: Mapped[float] = mapped_column(
        Numeric(18, 2),
        nullable=False,
        default=0,
        doc="Final quotation amount after discounts, taxes and additional charges.",
    )

    remarks: Mapped[str | None] = mapped_column(
        String(500),
        nullable=True,
        doc="Internal remarks or supplier notes.",
    )

    status_id: Mapped[int] = mapped_column(
        ForeignKey("journal_statuses.id"),
        nullable=False,
        index=True,
        doc="Current workflow status of the supplier quotation.",
    )

    is_selected: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
        doc="Indicates whether this quotation was selected for Purchase Order creation.",
    )

    # ------------------------------------------------------------------
    # Relationships
    # ------------------------------------------------------------------

    company: Mapped["Company"] = relationship()

    branch: Mapped["Branch"] = relationship()

    request_for_quotation: Mapped["RequestForQuotation"] = relationship(
        back_populates="supplier_quotations",
    )

    supplier: Mapped["Party"] = relationship()

    currency: Mapped["Currency"] = relationship()

    status: Mapped["JournalStatus"] = relationship()

    items: Mapped[list["SupplierQuotationItem"]] = relationship(
        back_populates="supplier_quotation",
        cascade="all, delete-orphan",
    )

    purchase_orders: Mapped[list["PurchaseOrder"]] = relationship(
        back_populates="supplier_quotation",
    )