from __future__ import annotations

from decimal import Decimal
from typing import TYPE_CHECKING
from uuid import UUID

from sqlalchemy import (
    Boolean,
    ForeignKey,
    Numeric,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database.base import AuditModel

if TYPE_CHECKING:
    from app.models.accounting.ledger import Ledger
    from app.models.company import Company
    from app.models.currency.currency import Currency
    from app.models.party.party_address import PartyAddress
    from app.models.party.party_attachment import PartyAttachment
    from app.models.party.party_bank_account import PartyBankAccount
    from app.models.party.party_contact import PartyContact
    from app.models.party.party_group import PartyGroup
    from app.models.party.party_type_mapping import PartyTypeMapping
    from app.models.party.party_tax_registration import PartyTaxRegistration
    from app.models.party.party_credit_limit import PartyCreditLimit


class Party(AuditModel):
    """
    Represents a business entity that interacts with the company.

    Purpose:
        Party is the central master for all external business entities
        that the organization conducts business with. Instead of creating
        separate Customer, Supplier, Transporter, Dealer, or Contractor
        tables, the ERP stores them in a single Party master.

        Each Party can be assigned one or more business roles through
        PartyTypeMapping, allowing a single organization to act in
        multiple capacities.

    Examples:
        - Customer
        - Supplier
        - Customer & Supplier
        - Transporter
        - Contractor
        - Dealer
        - Distributor
        - Manufacturer
        - Service Provider

    Why this model exists:
        A business partner may simultaneously be:

            • Customer
            • Supplier
            • Distributor

        Instead of duplicating the same company multiple times,
        a single Party record is maintained while PartyTypeMapping
        defines its business roles.

    ERP Workflow:

        Company
            │
            ▼
        Party
            │
            ├── Party Types
            ├── Contacts
            ├── Addresses
            ├── Bank Accounts
            ├── Attachments
            └── Ledger

    Business Benefits:
        - Single source of truth for business partners.
        - Eliminates duplicate customer/supplier records.
        - Supports multiple business roles.
        - Simplifies accounting integration.
        - Centralizes addresses, contacts and bank accounts.
        - Easily extensible for future ERP modules.

    Accounting Integration:
        Every Party is associated with an accounting Ledger.
        Financial transactions generated by Sales, Purchase,
        Payments and Receipts are ultimately posted to the
        linked ledger.

    Relationships:
        Company
            └── Party

        PartyGroup
            └── Party

        Ledger
            └── Party

        Currency
            └── Party

        Party
            ├── PartyTypeMapping
            ├── PartyContact
            ├── PartyAddress
            ├── PartyBankAccount
            └── PartyAttachment
    """

    __tablename__ = "parties"

    __table_args__ = (
        UniqueConstraint(
            "company_id",
            "code",
            name="uq_party_company_code",
        ),
        UniqueConstraint(
            "company_id",
            "name",
            name="uq_party_company_name",
        ),
    )

    company_id: Mapped[UUID] = mapped_column(
        ForeignKey("companies.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        doc="Company that owns this party.",
    )

    party_group_id: Mapped[UUID | None] = mapped_column(
        ForeignKey("party_groups.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
        doc="Optional group used to classify the party for reporting and organization.",
    )

    ledger_id: Mapped[UUID] = mapped_column(
        ForeignKey("ledgers.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
        doc="Ledger associated with this party for accounting transactions.",
    )

    currency_id: Mapped[UUID | None] = mapped_column(
        ForeignKey("currencies.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
        doc="Default transaction currency for the party.",
    )

    code: Mapped[str] = mapped_column(
        String(30),
        nullable=False,
        index=True,
        doc="Unique business code identifying the party within the company.",
    )

    name: Mapped[str] = mapped_column(
        String(200),
        nullable=False,
        index=True,
        doc="Official legal or registered name of the party.",
    )

    display_name: Mapped[str | None] = mapped_column(
        String(200),
        nullable=True,
        index=True,
        doc="Friendly name displayed in the ERP interface and reports.",
    )

    tax_number: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
        doc="Tax registration number such as GSTIN, VAT Number or Tax ID.",
    )

    registration_number: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
        doc="Business registration or company incorporation number.",
    )

    website: Mapped[str | None] = mapped_column(
        String(255),
        nullable=True,
        doc="Official website of the party.",
    )

    credit_limit: Mapped[Decimal] = mapped_column(
        Numeric(18, 2),
        nullable=False,
        default=Decimal("0.00"),
        doc="Maximum credit limit permitted for this party.",
    )

    notes: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        doc="Internal remarks or additional information about the party.",
    )

    is_active: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
        index=True,
        doc="Indicates whether the party is active and available for transactions.",
    )

    # Relationships

    company: Mapped["Company"] = relationship(
        back_populates="parties",
        lazy="selectin",
        doc="Company that owns this party.",
    )

    party_group: Mapped["PartyGroup | None"] = relationship(
        back_populates="parties",
        lazy="selectin",
        doc="Classification group assigned to this party.",
    )

    ledger: Mapped["Ledger"] = relationship(
        lazy="selectin",
        doc="Accounting ledger associated with the party.",
    )

    currency: Mapped["Currency | None"] = relationship(
        lazy="selectin",
        doc="Default transaction currency.",
    )

    party_type_mappings: Mapped[list["PartyTypeMapping"]] = relationship(
        back_populates="party",
        cascade="all, delete-orphan",
        lazy="selectin",
        doc="Business roles assigned to this party (Customer, Supplier, Transporter, etc.).",
    )

    contacts: Mapped[list["PartyContact"]] = relationship(
        back_populates="party",
        cascade="all, delete-orphan",
        lazy="selectin",
        doc="Contact persons associated with the party.",
    )

    addresses: Mapped[list["PartyAddress"]] = relationship(
        back_populates="party",
        cascade="all, delete-orphan",
        lazy="selectin",
        doc="Addresses associated with the party.",
    )

    bank_accounts: Mapped[list["PartyBankAccount"]] = relationship(
        back_populates="party",
        cascade="all, delete-orphan",
        lazy="selectin",
        doc="Bank accounts belonging to the party.",
    )

    attachments: Mapped[list["PartyAttachment"]] = relationship(
        back_populates="party",
        cascade="all, delete-orphan",
        lazy="selectin",
        doc="Documents and attachments related to the party.",
    )
    tax_registrations: Mapped[list["PartyTaxRegistration"]] = relationship(
        back_populates="party",
        cascade="all, delete-orphan",
        lazy="selectin",
        doc="Collection of tax registrations associated with the Party.",
    )
    credit_limits: Mapped[list["PartyCreditLimit"]] = relationship(
        back_populates="party",
        cascade="all, delete-orphan",
        lazy="selectin",
        doc="Collection of credit limit policies assigned to the Party.",
    )
