from __future__ import annotations

from datetime import date, datetime
from decimal import Decimal
from typing import TYPE_CHECKING
from uuid import UUID

from sqlalchemy import Date, DateTime, ForeignKey, Numeric, String, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database.base import AuditModel

if TYPE_CHECKING:
    from app.models.accounting.accounting_period import AccountingPeriod
    from app.models.accounting.fiscal_year import FiscalYear
    from app.models.accounting.journal_entry_line import JournalEntryLine
    from app.models.accounting.journal_status import JournalStatus
    from app.models.accounting.voucher_type import VoucherType
    from app.models.branch import Branch
    from app.models.company import Company
    from app.models.user import User


class JournalEntry(AuditModel):
    """
    Represents the header (master record) of a journal entry.

    A journal entry records a complete financial transaction in accordance with
    the double-entry accounting system. It contains the common information for
    the transaction, while the individual debit and credit postings are stored
    in the associated JournalEntryLine records.

    Every financial transaction generated by the ERP—including Sales, Purchase,
    Receipt, Payment, Inventory, Payroll, Asset Depreciation, Tax, and Manual
    Journal Vouchers—ultimately creates a journal entry.

    Purpose:
        - Acts as the master record for an accounting transaction.
        - Groups multiple debit and credit lines into a single transaction.
        - Tracks voucher information and transaction metadata.
        - Associates the transaction with a company, branch, fiscal year,
          accounting period, and voucher type.
        - Maintains the workflow status of the transaction
          (Draft, Posted, Cancelled, Reversed).
        - Stores the total debit and total credit amounts for validation.
        - Records posting information for audit and compliance.

    Accounting Rule:
        A journal entry must contain at least two journal entry lines and the
        total debit amount must always equal the total credit amount.

    Example:

        Sales Invoice

            Journal Entry
            -----------------------------
            Voucher No : SV000001
            Date       : 15-Apr-2026
            Voucher    : Sales Voucher

            Journal Entry Lines

            ----------------------------------------------
            Customer A/C            Dr   ₹11,800.00
                To Sales Revenue         ₹10,000.00
                To Output GST             ₹1,800.00
            ----------------------------------------------

    Another Example:

        Payment Voucher

            Bank A/C                Cr   ₹25,000.00
            Salary Expense          Dr   ₹25,000.00

    Relationships:
        Company
            └── JournalEntry

        FiscalYear
            └── JournalEntry

        AccountingPeriod
            └── JournalEntry

        VoucherType
            └── JournalEntry

        JournalEntry
            └── JournalEntryLine (One-to-Many)

    The JournalEntry represents the transaction header, while the
    JournalEntryLine records represent the individual ledger postings that
    affect account balances.
    """

    __tablename__ = "journal_entries"

    __table_args__ = (
        UniqueConstraint(
            "company_id",
            "voucher_no",
            name="uq_journal_entry_company_voucher_no",
        ),
    )

    company_id: Mapped[UUID] = mapped_column(
        ForeignKey("companies.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        doc="Company that owns this journal entry.",
    )

    branch_id: Mapped[UUID] = mapped_column(
        ForeignKey("branches.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
        doc="Branch where the transaction was recorded.",
    )

    fiscal_year_id: Mapped[UUID] = mapped_column(
        ForeignKey("fiscal_years.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
        doc="Fiscal year of the transaction.",
    )

    accounting_period_id: Mapped[UUID] = mapped_column(
        ForeignKey("accounting_periods.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
        doc="Accounting period of the transaction.",
    )

    voucher_type_id: Mapped[UUID] = mapped_column(
        ForeignKey("voucher_types.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
        doc="Voucher type of the journal entry.",
    )

    status_id: Mapped[UUID] = mapped_column(
        ForeignKey("journal_statuses.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
        doc="Current status of the journal entry.",
    )

    voucher_no: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        doc="Unique voucher number within the company.",
    )

    transaction_date: Mapped[date] = mapped_column(
        Date,
        nullable=False,
        doc="Accounting date of the journal entry.",
    )

    reference_no: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
        doc="External reference number.",
    )

    narration: Mapped[str | None] = mapped_column(
        String(500),
        nullable=True,
        doc="Description of the transaction.",
    )

    total_debit: Mapped[Decimal] = mapped_column(
        Numeric(18, 2),
        nullable=False,
        default=0,
        doc="Total debit amount.",
    )

    total_credit: Mapped[Decimal] = mapped_column(
        Numeric(18, 2),
        nullable=False,
        default=0,
        doc="Total credit amount.",
    )

    posted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        doc="Timestamp when the journal entry was posted.",
    )

    posted_by_id: Mapped[UUID | None] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
        doc="User who posted the journal entry.",
    )

    company: Mapped["Company"] = relationship(
        back_populates="journal_entries",
    )

    branch: Mapped["Branch"] = relationship(
        back_populates="journal_entries",
    )

    fiscal_year: Mapped["FiscalYear"] = relationship(
        back_populates="journal_entries",
    )

    accounting_period: Mapped["AccountingPeriod"] = relationship(
        back_populates="journal_entries",
    )

    voucher_type: Mapped["VoucherType"] = relationship(
        back_populates="journal_entries",
    )

    status: Mapped["JournalStatus"] = relationship(
        back_populates="journal_entries",
    )

    posted_by: Mapped["User | None"] = relationship(
        foreign_keys=[posted_by_id],
    )

    journal_entry_lines: Mapped[list["JournalEntryLine"]] = relationship(
        back_populates="journal_entry",
        cascade="all, delete-orphan",
    )
