from __future__ import annotations

from datetime import date
from typing import TYPE_CHECKING
from uuid import UUID

from sqlalchemy import Boolean, Date, ForeignKey, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database.base import AuditModel

if TYPE_CHECKING:
    from app.models.company.company import Company
    from app.models.company.branch import Branch
    from app.models.user.user import User
    from app.models.purchase.purchase_requisition_item import PurchaseRequisitionItem
    from app.models.purchase.purchase_approval import PurchaseApproval
    from app.models.purchase.purchase_attachment import PurchaseAttachment
    from app.models.accounting.journal_status import JournalStatus


class PurchaseRequisition(AuditModel):
    """
    Represents an internal request to procure goods or services.

    Purpose:
        A Purchase Requisition (PR) is the starting point of the purchasing
        lifecycle. It is created by an employee or department whenever goods,
        materials, assets, or services are required.

        The Purchase Requisition itself does not create any financial
        transaction. Instead, it acts as an approval and planning document
        before requesting quotations from suppliers.

        Once approved, one or more Request For Quotations (RFQs) can be
        generated from the requisition.

    ERP Workflow:

        Employee
            │
            ▼
        Purchase Requisition
            │
            ▼
        Approval
            │
            ▼
        Request For Quotation
            │
            ▼
        Supplier Quotation
            │
            ▼
        Purchase Order
            │
            ▼
        Purchase Receipt
            │
            ▼
        Purchase Invoice

    Business Benefits:
        - Standardizes internal purchase requests.
        - Prevents unauthorized purchasing.
        - Supports approval workflows.
        - Tracks departmental procurement.
        - Enables budgeting and planning.
        - Creates complete procurement audit trails.

    Typical Usage:

        Production Department
            Requests raw materials.

        Maintenance Department
            Requests spare parts.

        HR Department
            Requests office furniture.

        IT Department
            Requests laptops and software licenses.

    Relationships:

        Purchase Requisition
            ├── PurchaseRequisitionItem
            ├── PurchaseApproval
            ├── PurchaseAttachment
            └── RequestForQuotation

    Example:

        Requisition No:
            PR-2026-00015

        Requested By:
            Rahul

        Department:
            Production

        Required Date:
            15-Aug-2026

        Items:
            • Steel Rod
            • Lubricant
            • Safety Gloves

        Status:
            Approved
    """

    __tablename__ = "purchase_requisitions"

    requisition_no: Mapped[str] = mapped_column(
        String(30),
        nullable=False,
        unique=True,
        index=True,
        doc="Unique purchase requisition number generated by the ERP.",
    )

    requisition_date: Mapped[date] = mapped_column(
        Date,
        nullable=False,
        doc="Date on which the purchase requisition was created.",
    )

    company_id: Mapped[UUID] = mapped_column(
        ForeignKey("companies.id"),
        nullable=False,
        index=True,
        doc="Company that owns this purchase requisition.",
    )

    branch_id: Mapped[UUID] = mapped_column(
        ForeignKey("branches.id"),
        nullable=False,
        index=True,
        doc="Branch where the purchase requirement originated.",
    )

    requested_by_id: Mapped[UUID] = mapped_column(
        ForeignKey("users.id"),
        nullable=False,
        index=True,
        doc="Employee or user who raised the purchase requisition.",
    )

    department_id: Mapped[UUID | None] = mapped_column(
        nullable=True,
        index=True,
        doc="Department requesting the purchase.",
    )

    required_date: Mapped[date | None] = mapped_column(
        Date,
        nullable=True,
        doc="Expected date on which the requested items are required.",
    )

    priority: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        default="NORMAL",
        doc="Priority of the requisition. Example: LOW, NORMAL, HIGH, URGENT.",
    )

    status_id: Mapped[UUID] = mapped_column(
        ForeignKey("journal_statuses.id"),
        nullable=False,
        index=True,
        doc="Current workflow status of the purchase requisition.",
    )

    remarks: Mapped[str | None] = mapped_column(
        String(500),
        nullable=True,
        doc="Additional notes or justification for the purchase request.",
    )

    is_closed: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
        doc="Indicates whether the requisition has been completely fulfilled.",
    )

    is_cancelled: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
        doc="Indicates whether the requisition has been cancelled.",
    )

    # Relationships

    company: Mapped["Company"] = relationship()

    branch: Mapped["Branch"] = relationship()

    requested_by: Mapped["User"] = relationship()

    status: Mapped["JournalStatus"] = relationship()

    items: Mapped[list["PurchaseRequisitionItem"]] = relationship(
        back_populates="purchase_requisition",
        cascade="all, delete-orphan",
    )

    approvals: Mapped[list["PurchaseApproval"]] = relationship(
        back_populates="purchase_requisition",
        cascade="all, delete-orphan",
    )

    attachments: Mapped[list["PurchaseAttachment"]] = relationship(
        back_populates="purchase_requisition",
        cascade="all, delete-orphan",
    )

    request_for_quotations: Mapped[list["RequestForQuotation"]] = relationship(
        back_populates="purchase_requisition",
        cascade="all, delete-orphan",
    )
